# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cricle-test
    steps:
      - checkout

  get_dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cricle-test
    steps:
      - restore_cache:
          keys:
          - cricle-test-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - cricle-test-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: cricle-test-{{ checksum "pom.xml" }}

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cricle-test
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - run: mvn compile

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cricle-test
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      # run tests!
      - run: |
          mvn integration-test
          mkdir target/junit
      - store_test_results:
          path: target/junit

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - get_dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - get_dependencies
      - test:
          requires:
            - get_dependencies
